<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_68ff203c2999d',
	'title' => 'block:txt-t',
	'fields' => array(
		array(
			'key' => 'field_68ff203c324aa',
			'label' => 'Заголовок',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'текст обернутый в &lt;span&gt;&lt;/span&gt; будет выделен цветом',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68ff204ef0133',
			'label' => 'Вкладки',
			'name' => 'tabs',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Добавить вкладку',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_68ff208ef0134',
					'label' => 'Название',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68ff204ef0133',
				),
				array(
					'key' => 'field_68ff20a4f0135',
					'label' => 'Блок с фоном',
					'name' => 'header',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_68ff20cef0136',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68ff20e2f0138',
							'label' => 'Фон',
							'name' => 'bg',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'return_format' => 'id',
							'library' => 'all',
							'upload_folder' => '',
							'acfe_thumbnail' => 0,
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'thumbnail',
						),
						array(
							'key' => 'field_68ff20d9f0137',
							'label' => 'Текст',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'acfe_wysiwyg_height' => 300,
							'acfe_wysiwyg_max_height' => '',
							'acfe_wysiwyg_valid_elements' => '',
							'acfe_wysiwyg_custom_style' => '',
							'acfe_wysiwyg_disable_wp_style' => 0,
							'acfe_wysiwyg_autoresize' => 0,
							'acfe_wysiwyg_disable_resize' => 0,
							'acfe_wysiwyg_remove_path' => 0,
							'acfe_wysiwyg_menubar' => 0,
							'acfe_wysiwyg_transparent' => 0,
							'acfe_wysiwyg_merge_toolbar' => 0,
							'acfe_wysiwyg_custom_toolbar' => 0,
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_wysiwyg_auto_init' => 0,
							'acfe_wysiwyg_min_height' => 300,
							'acfe_wysiwyg_toolbar_buttons' => array(
							),
						),
					),
					'acfe_group_modal_close' => 0,
					'acfe_group_modal_button' => '',
					'acfe_group_modal_size' => 'large',
					'parent_repeater' => 'field_68ff204ef0133',
				),
				array(
					'key' => 'field_68ff203c32970',
					'label' => 'Текстовые блоки',
					'name' => 'txt',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => 'field_68ff07b34aa3e',
					'button_label' => 'Добавить блок',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_68ff203c39e0e',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_68ff203c32970',
						),
						array(
							'key' => 'field_68ff203c3a542',
							'label' => 'Текст',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'acfe_wysiwyg_auto_init' => 0,
							'acfe_wysiwyg_height' => 300,
							'acfe_wysiwyg_max_height' => '',
							'acfe_wysiwyg_valid_elements' => '',
							'acfe_wysiwyg_custom_style' => '',
							'acfe_wysiwyg_disable_wp_style' => 0,
							'acfe_wysiwyg_autoresize' => 0,
							'acfe_wysiwyg_disable_resize' => 0,
							'acfe_wysiwyg_remove_path' => 0,
							'acfe_wysiwyg_menubar' => 0,
							'acfe_wysiwyg_transparent' => 0,
							'acfe_wysiwyg_merge_toolbar' => 0,
							'acfe_wysiwyg_custom_toolbar' => 0,
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_wysiwyg_min_height' => 300,
							'acfe_wysiwyg_toolbar_buttons' => array(
							),
							'parent_repeater' => 'field_68ff203c32970',
						),
					),
					'parent_repeater' => 'field_68ff204ef0133',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1761552332,
));

endif;