<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6900be4d511aa',
	'title' => 'block:cards-c',
	'fields' => array(
		array(
			'key' => 'field_6900be587d8e9',
			'label' => 'Блоки',
			'name' => 'blocks',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_6900be4d5afe6',
			'button_label' => 'Добавить блок',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6900be4d5afe6',
					'label' => 'Заголовок',
					'name' => 'title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'текст обернутый в &lt;span&gt;&lt;/span&gt; будет выделен цветом',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6900be587d8e9',
				),
				array(
					'key' => 'field_6900be937d8eb',
					'label' => 'Характеристики',
					'name' => 'chars',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Добавить элемент',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6900bea87d8ec',
							'label' => 'Название',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6900be937d8eb',
						),
						array(
							'key' => 'field_6900beb17d8ed',
							'label' => 'Значение',
							'name' => 'value',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'acfe_textarea_code' => 0,
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'rows' => 4,
							'placeholder' => '',
							'new_lines' => 'br',
							'parent_repeater' => 'field_6900be937d8eb',
						),
					),
					'parent_repeater' => 'field_6900be587d8e9',
				),
				array(
					'key' => 'field_6900becc7d8ee',
					'label' => 'Текст',
					'name' => 'text',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_wysiwyg_auto_init' => 0,
					'acfe_wysiwyg_height' => 300,
					'acfe_wysiwyg_max_height' => '',
					'acfe_wysiwyg_valid_elements' => '',
					'acfe_wysiwyg_custom_style' => '',
					'acfe_wysiwyg_disable_wp_style' => 0,
					'acfe_wysiwyg_autoresize' => 0,
					'acfe_wysiwyg_disable_resize' => 0,
					'acfe_wysiwyg_remove_path' => 0,
					'acfe_wysiwyg_menubar' => 0,
					'acfe_wysiwyg_transparent' => 0,
					'acfe_wysiwyg_merge_toolbar' => 0,
					'acfe_wysiwyg_custom_toolbar' => 0,
					'allow_in_bindings' => 0,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'acfe_wysiwyg_min_height' => 300,
					'acfe_wysiwyg_toolbar_buttons' => array(
					),
					'parent_repeater' => 'field_6900be587d8e9',
				),
				array(
					'key' => 'field_6900bee27d8ef',
					'label' => 'Кол-во карточек в ряд',
					'name' => 'cards-count',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						2 => '2',
						3 => '3',
					),
					'default_value' => 2,
					'return_format' => 'value',
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'layout' => 'horizontal',
					'parent_repeater' => 'field_6900be587d8e9',
				),
				array(
					'key' => 'field_6900bf007d8f0',
					'label' => 'Карточки',
					'name' => 'cards',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'block',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Добавить карточку',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6900bf127d8f1',
							'label' => 'Название',
							'name' => 'name',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 0,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_6900bf007d8f0',
						),
						array(
							'key' => 'field_6900bf227d8f2',
							'label' => 'Изображение',
							'name' => 'img',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => 'Изображение вставляется в полном размере',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'return_format' => 'id',
							'library' => 'all',
							'upload_folder' => '',
							'acfe_thumbnail' => 0,
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
							'parent_repeater' => 'field_6900bf007d8f0',
						),
						array(
							'key' => 'field_6900bf3b7d8f3',
							'label' => 'Текст',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'acfe_wysiwyg_height' => 300,
							'acfe_wysiwyg_max_height' => '',
							'acfe_wysiwyg_valid_elements' => '',
							'acfe_wysiwyg_custom_style' => '',
							'acfe_wysiwyg_disable_wp_style' => 0,
							'acfe_wysiwyg_autoresize' => 0,
							'acfe_wysiwyg_disable_resize' => 0,
							'acfe_wysiwyg_remove_path' => 0,
							'acfe_wysiwyg_menubar' => 0,
							'acfe_wysiwyg_transparent' => 0,
							'acfe_wysiwyg_merge_toolbar' => 0,
							'acfe_wysiwyg_custom_toolbar' => 0,
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'acfe_wysiwyg_auto_init' => 0,
							'acfe_wysiwyg_min_height' => 300,
							'acfe_wysiwyg_toolbar_buttons' => array(
							),
							'parent_repeater' => 'field_6900bf007d8f0',
						),
					),
					'parent_repeater' => 'field_6900be587d8e9',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1761657185,
));

endif;